name: Solang Parser Workflow

on:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Clone Gambit repository
        run: |
          cd ~
          git clone -b ben/build_scripts https://github.com/Certora/Gambit
          pwd
          ls -a
          ls Gambit
          ls Gambit/scripts
          chmod +x Gambit/scripts/run_on_hardhat.py
          ln -s $PWD/Gambit/scripts/run_on_hardhat.py /usr/local/bin/run_on_hardhat

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Install this repo
        run: cargo install --path .

      - name: Download and install solc 0.8.17
        run: |
          wget https://github.com/ethereum/solidity/releases/download/v0.8.17/solc-static-linux
          chmod +x solc-static-linux
          sudo mv solc-static-linux /usr/local/bin/solc8.17

      - name: Download and install solc 0.8.15
        run: |
          wget https://github.com/ethereum/solidity/releases/download/v0.8.15/solc-static-linux
          chmod +x solc-static-linux
          sudo mv solc-static-linux /usr/local/bin/solc8.15

      - name: Download and install solc 0.8.20
        run: |
          wget https://github.com/ethereum/solidity/releases/download/v0.8.20/solc-static-linux
          chmod +x solc-static-linux
          sudo mv solc-static-linux /usr/local/bin/solc8.20

      - name: Collect Data on Seaport
        run: |
          cd ~
          git clone https://github.com/ProjectOpenSea/seaport
          cd seaport
          npm install
          run_on_hardhat . contracts --collect_data --solc solc8.17 --solang_parser
          echo "# Seaport Summary" >> ~/summary.md
          cat summary.md >> ~/summary.md

      - name: Collect Data on Solmate
        run: |
          cd ~
          git clone https://github.com/transmissions11/solmate
          cd solmate
          npm install
          run_on_hardhat . src/auth src/mixins src/tokens src/utils  --collect_data --solc solc8.15 --solang_parser --import_paths . src lib
          echo "# Solmate Summary" >> ~/summary.md
          cat summary.md >> ~/summary.md

      - name: Collect Data on OpenZeppelin
        run: |
          cd ~
          git clone https://github.com/OpenZeppelin/openzeppelin-contracts
          cd openzeppelin-contracts
          npm install
          run_on_hardhat . contracts --collect_data --solc solc8.20 --solang_parser
          echo "# OpenZeppelin Summary" >> ~/summary.md
          cat summary.md >> ~/summary.md

      - uses: actions/upload-artifact@v3
        with:
          name: tool-run-data
          path: ~/**/data_collect
        if: always()

      - uses: actions/upload-artifact@v3
        with:
          name: summary
          path: ~/summary.md
        if: always()
