name: Solang Parser Workflow

on:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches:
      - main

jobs:
  build:
    if: github.actor != 'github-actions[bot]' && github.actor != 'github-actions'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install run_on_hardhat.py Script
        run: |
          chmod +x python/run_on_hardhat.py
          ln -s "$PWD"/python/run_on_hardhat.py /usr/local/bin/run_on_hardhat

      - name: Install run_on_repo.sh Script
        run: |
          chmod +x bash/run_on_repo.sh
          ln -s "$PWD"/bash/run_on_repo.sh /usr/local/bin/run_on_repo

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Install this repo
        run: cargo install --path .

      - name: Download and install solc 0.8.10
        run: |
          wget https://github.com/ethereum/solidity/releases/download/v0.8.10/solc-static-linux
          chmod +x solc-static-linux
          sudo mv solc-static-linux /usr/local/bin/solc8.10

      - name: Download and install solc 0.8.15
        run: |
          wget https://github.com/ethereum/solidity/releases/download/v0.8.15/solc-static-linux
          chmod +x solc-static-linux
          sudo mv solc-static-linux /usr/local/bin/solc8.15

      - name: Download and install solc 0.8.17
        run: |
          wget https://github.com/ethereum/solidity/releases/download/v0.8.17/solc-static-linux
          chmod +x solc-static-linux
          sudo mv solc-static-linux /usr/local/bin/solc8.17

      - name: Download and install solc 0.8.20
        run: |
          wget https://github.com/ethereum/solidity/releases/download/v0.8.20/solc-static-linux
          chmod +x solc-static-linux
          sudo mv solc-static-linux /usr/local/bin/solc8.20

      # [Collect Data From Different OS Repos]
      - name: "Setup Summary"
        run: |
          echo "# Summary" > ~/summary.md

      - name: Collect Data on Seaport
        run: |
          run_on_repo Seaport https://github.com/ProjectOpenSea/seaport solc8.17 contracts

      - name: Collect Data on Solmate
        run: |
          run_on_repo Solmate https://github.com/transmissions11/solmate  solc8.15  src/auth src/mixins src/tokens src/utils

      - name: Collect Data on OpenZeppelin
        run: |
          run_on_repo "OpenZeppelin Contracts" https://github.com/OpenZeppelin/openzeppelin-contracts  solc8.20 contracts

      - name: Collect Data on GMX Synthetics
        run: |
          run_on_repo "GMX Synthetics" https://github.com/Certora/gmx-synthetics_all solc8.20 contracts

      - name: "Run on AAVE StarkNet Bridge"
        run: run_on_repo "AAVE StarkNet Bridge" https://github.com/Certora/aave-starknet-bridge contracts

      # Combine summary jsons
      - name: Combine JSONs
        run: |
          COMBINE_JSONS_PY="$PWD"/python/combine_jsons.py
          cd ~
          python3 "$COMBINE_JSONS_PY" *_summary.json

      # [Push Summary to Repo]
      - name: Configure Git
        # if: github.event_name == 'schedule'
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Commit and Push Summary
        # if: github.event_name == 'schedule'
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PUSH_ACCESS_PAT }}
        run: |
          # Get a filename for current run based on date
          DATE=$(date +"%Y-%m-%d")
          MD_FILENAME="nightlies/markdown/$DATE.md"
          JSON_FILENAME="nightlies/json/$DATE.json"
          if [ ! -e nightlies ]; then
            mkdir nightlies
          fi
          if [ ! -e nightlies/markdown ]; then
            mkdir nightlies/markdown
          fi
          if [ ! -e nightlies/json ]; then
            mkdir nightlies/json
          fi
          cp ~/summary.md "$MD_FILENAME"
          cp ~/summary.json "$JSON_FILENAME"
          cp "$MD_FILENAME" nightlies/current.md
          cp "$JSON_FILENAME" nightlies/current.json
          git add "$MD_FILENAME"
          git add "$JSON_FILENAME"
          git add nightlies/current.md

          git diff --cached --quiet || git commit -m "Update nightlies"
          git push

      - uses: actions/upload-artifact@v3
        # if: github.event_name == 'schedule'
        with:
          name: tool-run-data
          path: ~/**/data_collect
