name: Solang Parser Workflow

on:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches:
      - main

jobs:
  build:
    if: github.actor != 'github-actions[bot]' && github.actor != 'github-actions'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install Run On Hardhat Script
        run: |
          chmod +x python/run_on_hardhat.py
          ln -s "$PWD"/python/run_on_hardhat.py /usr/local/bin/run_on_hardhat

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Install this repo
        run: cargo install --path .

      - name: Download and install solc 0.8.17
        run: |
          wget https://github.com/ethereum/solidity/releases/download/v0.8.17/solc-static-linux
          chmod +x solc-static-linux
          sudo mv solc-static-linux /usr/local/bin/solc8.17

      - name: Download and install solc 0.8.15
        run: |
          wget https://github.com/ethereum/solidity/releases/download/v0.8.15/solc-static-linux
          chmod +x solc-static-linux
          sudo mv solc-static-linux /usr/local/bin/solc8.15

      - name: Download and install solc 0.8.20
        run: |
          wget https://github.com/ethereum/solidity/releases/download/v0.8.20/solc-static-linux
          chmod +x solc-static-linux
          sudo mv solc-static-linux /usr/local/bin/solc8.20

      # [Collect Data From Different OS Repos]
      - name: "Setup Summary"
        run: |
          echo "# Summary" > ~/summary.md
      - name: Collect Data on Seaport
        run: |
          cd ~
          git clone https://github.com/ProjectOpenSea/seaport
          cd seaport
          npm install
          run_on_hardhat . contracts --collect_data --solc solc8.17 --solang_parser
          echo "## Seaport Summary" >> ~/summary.md
          cat summary.md >> ~/summary.md
          mv summary.json ~/seaport_summary.json

      - name: Collect Data on Solmate
        run: |
          cd ~
          git clone https://github.com/transmissions11/solmate
          cd solmate
          npm install
          run_on_hardhat . src/auth src/mixins src/tokens src/utils  --collect_data --solc solc8.15 --solang_parser --import_paths . src lib
          echo "## Solmate Summary" >> ~/summary.md
          cat summary.md >> ~/summary.md
          mv summary.json ~/solmate_summary.json

      - name: Collect Data on OpenZeppelin
        run: |
          cd ~
          git clone https://github.com/OpenZeppelin/openzeppelin-contracts
          cd openzeppelin-contracts
          npm install
          run_on_hardhat . contracts --collect_data --solc solc8.20 --solang_parser
          echo "## OpenZeppelin Summary" >> ~/summary.md
          cat summary.md >> ~/summary.md
          mv summary.json ~/openzeppelin_summary.json

      # Combine summary jsons
      - name: Combine JSONs
        run: |
          COMBINE_JSONS_PY="$(PWD)"/python/combine_jsons.py
          cd ~
          python3 "$COMBINE_JSONS_PY" *_summary.json

      # [Push Summary to Repo]
      - name: Configure Git
        if: github.event_name == 'schedule'
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Commit and Push Summary
        if: github.event_name == 'schedule'
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PUSH_ACCESS_PAT }}
        run: |
          # Get a filename for current run based on date
          DATE=$(date +"%Y-%m-%d")
          MD_FILENAME="nightlies/markdown/$DATE.md"
          JSON_FILENAME="nightlies/json/$DATE.json"
          if [ ! -e nightlies ]; then
            mkdir nightlies
          fi
          if [ ! -e nightlies/markdown ]; then
            mkdir nightlies/markdown
          fi
          if [ ! -e nightlies/json ]; then
            mkdir nightlies/json
          fi
          cp ~/summary.md "$MD_FILENAME"
          cp ~/summary.json "$JSON_FILENAME"
          if [ -e nightlies/current.md ] ; then 
            rm nightlies/current.md
          fi
          cp "$MD_FILENAME" nightlies/current.md
          git add "$MD_FILENAME"
          git add "$JSON_FILENAME"
          git add nightlies/current.md

          git diff --cached --quiet || git commit -m "Update nightlies"
          git push

      - uses: actions/upload-artifact@v3
        if: github.event_name == 'schedule'
        with:
          name: tool-run-data
          path: ~/**/data_collect

      - uses: actions/upload-artifact@v3
        if: github.event_name == 'schedule'
        with:
          name: summary
          path: ~/summary.md
