name: Solang Parser Workflow

on:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Download and install solc 0.8.17
        run: |
          wget https://github.com/ethereum/solidity/releases/download/v0.8.17/solc-static-linux
          chmod +x solc-static-linux
          sudo mv solc-static-linux /usr/local/bin/solc8.17

      - name: Clone SolangeParse4Debugging repository
        run: git clone https://github.com/bkushigian/SolangParse4Debugging

      - name: Clone Gambit repository
        run: |
          git clone https://github.com/Certora/Gambit
          chmod +x gambit/scripts/run_on_hardhat.py
          ln -s $PWD/gambit/scripts/run_on_hardhat.py /usr/local/bin/run_on_hardhat

      - name: Install solang_parser
        run: cd SolangParser4Debugging && cargo install --path .

      - name: Install Node.js and NPM
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Install Foundry Forge
        run: |
          curl -L https://foundry.paradigm.xyz | bash
          foundryup

      - name: Clone seaport repository and run npm install
        run: |
          git clone https://github.com/ProjectOpenSea/seaport
          cd seaport
          npm install
          run_on_hardhat . contracts --solc solc8.17 --solang_parser

      - name: Clone solmate repository and run npm install
        run: |
          git clone https://github.com/transmissions11/solmate
          cd solmate
          npm install
          run_on_hardhat . src/auth src/mixins src/tokens src/utils  --solc solc8.15 --import_paths . src lib
